<div class="page-margin">
	<div class="container">
		<h2 class="tag_page_title m5"><?php echo $wo['lang']['market']; ?></h2>
		<ul class="list-unstyled tag_page_nav">
			<?php if ($wo['config']['can_use_market']) { ?>
				<li class="separate"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-products'); ?>" data-ajax="?link1=my-products"><?php echo $wo['lang']['my_products'] ?></a></li>
			<?php } ?>
			<?php if ($wo['config']['store_system'] == 'on') { ?>
				<li><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=purchased'); ?>" data-ajax="?link1=purchased"><?php echo $wo['lang']['purchased'] ?></a></li>
				<li class="active"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=orders'); ?>" data-ajax="?link1=orders"><?php echo $wo['lang']['orders'] ?></a></li>
			<?php } ?>
			<li><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=products'); ?>" data-ajax="?link1=products"><?php echo $wo['lang']['market'] ?></a></li>
		</ul>
			
		<?php if (!empty($wo['orders']) && count($wo['orders']) > 0): ?>
			<div class="row">
				<?php echo($wo['html']); ?>
			</div>

			<?php if (count($wo['orders']) == 1){ ?>
				<div class="purchased_posts_load">
					<div class="load-more purchased_load-more">
						<button class="btn btn-default text-center pointer" onclick="Wo_LoadOrders();">
							<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"></path></svg></span> <?php echo $wo['lang']['load_more'] ?>
						</button>
					</div>
				</div>
			<?php } ?>
		<?php else: ?>
			<?php echo($wo['html']); ?>
		<?php endif; ?>
	</div>
	<!-- .row -->
</div>