<div class="lightbox-content post wo_imagecombo_lbox story_lightbox">
	<?php if (Wo_IsMobile() == false) { ?>
	<div class="story-img user_story_">
		<div class="valign tag_lbox_toolbar">
			<div class="btn btn-mat close-lightbox" onclick="window.history.back();">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M7.828 11H20v2H7.828l5.364 5.364-1.414 1.414L4 12l7.778-7.778 1.414 1.414z"></path></svg>
			</div>
		</div>
		<div class="tag_lbox_story_view create-story-view">
			<div class="tag_lbox_blur_img"><div class="tag_lbox_blur_img_innr" id="copy_story_bgdrop"></div></div>
			<div class="mfp-wrap"><span class="mfp_progress_line_"><span class="width_ load"></span><span></div>
			<div class="valign wo_story_header">
				<div class="valign wo_stor_h_info">
					<img src="<?php echo $wo['user']['avatar'];?>" alt="">
					<div class="wo_s_h_i_r">
						<div class="truncate bold user-name">
							<a href="<?php echo $wo['user']['url']; ?>"><?php echo $wo['user']['name'];?></a>
						</div>
						<span class="ajax-time"><?php echo $wo['lang']['time_just_now'] ?></span>
					</div>
				</div>
			</div>
			<div class="tag_lbox_img_innr">
				<div id="draggableHelper" class="dragable"></div>
				<div class="text-center draggableHelper_story_content" id="copy_story_desc"></div>
			</div>
		</div>
	</div>
	<?php } ?>
	<div class="tag_story_side">
		<h2 class="tag_page_title m5"><button type="button" class="btn create_story_navigation" onclick="window.history.back();"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z" fill="currentColor"></path></svg></button><?php echo $wo['lang']['create_new_status'] ?></h2>
		<div class="wow_sett_content tag_create_story">
			<form class="create-user-story form-horizontal" method="post">
				<label class="tag_field">
					<textarea name="description" id="whats_going" rows="3" onkeyup="document.getElementById('copy_story_desc').innerHTML = escapeHtml(this.value)" placeholder=" "></textarea>
					<span><?php echo $wo['lang']['whats_going']; ?></span>
				</label>
				<p class="bold"><?php echo $wo['lang']['media']; ?></p>
				<div class="tag_media_file mb-15 tag_media__storymedia" data-block="thumdrop-zone">
					<span class="valign pointer btn-file" onclick="$('#user-storymedia').trigger('click'); return false;">
						<span class="valign"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24"><path fill="currentColor" d="M17,10.5L21,6.5V17.5L17,13.5V17A1,1 0 0,1 16,18H4A1,1 0 0,1 3,17V7A1,1 0 0,1 4,6H16A1,1 0 0,1 17,7V10.5M10.91,9.55L9.2,11.82L10.5,13.55L9.77,14.09L7.73,11.36L5,15H15L10.91,9.55Z"></path></svg></span> <b class="truncate"><?php echo $wo['lang']['select']; ?> <?php echo $wo['lang']['photos']; ?> &amp; <?php echo $wo['lang']['videos']; ?></b>
					</span>
					<input type="file" name="statusMedia[]" id="user-storymedia" multiple>
				</div>
				<div id="custom_thumbnail" style="display: none;">
					<p class="bold"><?php echo $wo['lang']['custom_thumbnail']; ?></p>
					<div class="tag_media_file mb-15 tag_media__storymedia-2">
						<span class="valign pointer btn-file" onclick="$('#user-storymedia-2').trigger('click'); return false;">
							<span class="valign"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z"></path></svg></span> <b class="truncate"><?php echo $wo['lang']['select']; ?> <?php echo $wo['lang']['custom_thumbnail']; ?></b>
						</span>
						<input type="file" name="cover" id="user-storymedia-2">
					</div>
				</div>
				<div class="create-status-alert hidden">
					<div class="alert alert-danger"><?php echo $wo['lang']['max_number_status_6'] ?></div>
				</div>
				<div class="tag_pub_box_progress tag_pub_prod_progress">
					<div class="progress">
						<div class="progress-bar create-product-bar"></div> 
					</div>
					<div class="clear"></div>
				</div>
				<div class="text-center">
					<button class="btn btn-main btn-mat disable_btn" type="submit"><?php echo $wo['lang']['create']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>

<link rel="stylesheet" href="/pintura/pintura.css" />

<style>
    .my-editor {
      width: 100%;
      height: 100%;
	  position: relative;
	  z-index: 9999;
    }
</style>
<script>
  (async () => {
    let host = {
      clientId: "ea51ff7eabd642f78f13dab9732e8458",
      appName: "rougee_editor", 
      // ... other required properties
    }

    let config = { locale: 'en_US' }

    try {
      const ccEverywhere = await window.CCEverywhere.initialize(host, config);
      console.log('Initialization successful', ccEverywhere);

      // Now you can use ccEverywhere to create designs, handle image uploads, etc.
      // For example, to handle file input changes:
      const fileInput = document.querySelector('#user-storymedia');
      fileInput.addEventListener('change', () => {
        if (!fileInput.files.length) return;

        const selectedFile = fileInput.files[0];
        if (!selectedFile.type.startsWith('image/')) return;

        // Use ccEverywhere to edit the selected file, open modals, etc.
        // You need to check the CCEverywhere documentation for the correct methods and usage.
      });

    } catch (error) {
      console.error('Initialization failed', error);
    }
  })();
</script>
<script>
jQuery(document).ready(function($) {
    var thumb_drop_block = $("[data-block='thumdrop-zone']");

    if (typeof(window.FileReader) == 'undefined') {
      thumb_drop_block.find('.thumbnail-rendderer div').text('Drag drop is not supported in your browser!');
    }
    else{
      thumb_drop_block[0].ondragover = function() {
          thumb_drop_block.addClass('hover');
          return false;
      };
          
      thumb_drop_block[0].ondragleave = function() {
          thumb_drop_block.removeClass('hover');
          return false;
      };

      thumb_drop_block[0].ondrop = function(event) {
          event.preventDefault();
          thumb_drop_block.removeClass('hover');
          var file = event.dataTransfer.files;
          if (file.length > 6) {
          	$(".create-status-alert").removeClass('hidden');
          	return false;
          }
          if (file.length == 1) {
          	var ext = getExtension(file[0].name);
				    switch (ext.toLowerCase()) {
					    case 'm4v':
					    case 'avi':
					    case 'mpg':
					    case 'mp4':
					    $('#custom_thumbnail').slideDown();
				    }
          }
          $("#user-storymedia").prop('files', file);
		  $(".tag_media__storymedia .btn-file b").text(file.length + ' file(s) selected');
		  $("#draggableHelper, #copy_story_bgdrop").html("<img src='" + window.URL.createObjectURL(file[0]) + "' alt='Picture'>");
		  var numFiles = file.length;
		  if (numFiles > 1) {
			$("#draggableHelper").html('<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" height="48" width="48" viewBox="0 0 48 48"><path fill="currentColor" d="M35 41V7q1.4 0 2.2.725.8.725.8 2.275v28q0 1.55-.8 2.275Q36.4 41 35 41ZM7 44q-1.25 0-2.125-.875T4 41V7q0-1.25.875-2.125T7 4h20q1.25 0 2.125.875T30 7v34q0 1.25-.875 2.125T27 44Zm36-6.05V10.1q1 0 1.5.425T45 12.1v23.85q0 1.15-.5 1.575-.5.425-1.5.425Z"/></svg> '+ file.length + ' file(s) selected</div>');
		}
      };
    }
});
  
function getExtension(filename) {
	var parts = filename.split('.');
	return parts[parts.length - 1];
}
jQuery(document).ready(function($) {
	$("#user-storymedia").change(function () {
		$("#draggableHelper, #copy_story_bgdrop").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>");
		var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
		$(".tag_media__storymedia .btn-file b").text(filename);
        var numFiles = this.files.length;
		if (numFiles > 1) {
			$(".tag_media__storymedia .btn-file b").text(this.files.length + ' file(s) selected');
			$("#draggableHelper").html('<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" height="48" width="48" viewBox="0 0 48 48"><path fill="currentColor" d="M35 41V7q1.4 0 2.2.725.8.725.8 2.275v28q0 1.55-.8 2.275Q36.4 41 35 41ZM7 44q-1.25 0-2.125-.875T4 41V7q0-1.25.875-2.125T7 4h20q1.25 0 2.125.875T30 7v34q0 1.25-.875 2.125T27 44Zm36-6.05V10.1q1 0 1.5.425T45 12.1v23.85q0 1.15-.5 1.575-.5.425-1.5.425Z"/></svg> '+ this.files.length + ' file(s) selected</div>');
		}
        if (numFiles > 6) {
			$("#user-storymedia").val('');
			$(".create-status-alert").removeClass('hidden');
        }
        var ext = getExtension(this.files[0].name);
	    switch (ext.toLowerCase()) {
		    case 'm4v':
		    case 'avi':
		    case 'mpg':
		    case 'mp4':
		    return $('#custom_thumbnail').slideDown();
	    }
		$('#custom_thumbnail').slideUp();
	});
	$("#user-storymedia-2").change(function () {
		$("#draggableHelper, #copy_story_bgdrop").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>");
		var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
		$(".tag_media__storymedia-2 .btn-file b").text(filename);
        var numFiles = this.files.length;
        if (numFiles > 6) {
			$("#user-storymedia-2").val('');
			$(".create-status-alert").removeClass('hidden');
        }
	});
	
	var create_bar = $('.create-product-bar');
	$('.create-user-story').ajaxForm({
		url: Wo_Ajax_Requests_File() + '?f=status&s=new',
		type:"POST",
		beforeSend: function() {
			var percentVal = '0%';
			create_bar.width(percentVal);
			$('.create-user-story').find('.disable_btn').attr('disabled','disabled');
		},
		uploadProgress: function (event, position, total, percentComplete) {
			var percentVal = percentComplete + '%';
			create_bar.width(percentVal);
			$('.tag_pub_prod_progress').fadeIn(100);
		},
		success: function(data) {
			scrollToTop();
			if (data['status'] == 200) {
				$(".create-status-alert").removeClass('hidden').html('<div class="alert alert-success">'+ data['message'] +'</div>');
				window.location = '<?php echo $wo['config']['site_url']; ?>';
			} 
			else if (data['message']) {
				$(".create-status-alert").removeClass('hidden').html('<div class="alert alert-danger">' + data['message'] + '</div>');
			} else {
				if(data.invalid_file == 3){
					$("body").snackbar({
						message: "<?php echo $wo['lang']['adult_image_file']; ?>"
					});
				}
			} 
			$('.create-user-story').find('.disable_btn').removeAttr("disabled");
		}
	});
});
</script>