<h2 class="tag_page_title"><button type="button" class="btn setting_navigation" onclick="$('.tag_sett_sidebar').fadeIn(50);$('#tag_sett_right_prt').fadeOut(50);"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z" fill="currentColor"></path></svg></button> <?php echo $wo['lang']['tiers']; ?></h2>
<div class="wow_sett_content wow_content p20">
	<a href="javascript:void();" class="btn btn-main btn-mat mb-15" onclick="AddTier();"><?php echo $wo['lang']['add_tier']; ?></a>

	<div class="tier_page">
		<div>
			<p class="bold"><?php echo $wo['lang']['choose_offer_patrons']; ?></p>
			<?php echo $wo['tiers_html']; ?>
		</div>
	</div>
</div>

<script type="text/javascript">
	function EditTier(id) {
		$('.modal_edit_tier_modal_alert_'+id).empty();
		$("#edit_tier_modal_"+id).find('.btn-main').removeAttr('disabled')
		$("#edit_tier_modal_"+id).find('.btn-main').text("<?php echo $wo['lang']['edit']; ?>");
		$('#edit_tier_modal_'+id).modal('show');
		$("#select_tier_image_"+id).click(function(event) {
      $("#tier_image_"+id).click()
    });
    $("#tier_image_"+id).change(function(event) {
      $("#select_tier_image_"+id).html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
    });
	}
	function DeleteTier(id,type = 'show') {
		if (type == 'hide') {
	      $('#delete-tier').find('.btn-main').attr('onclick', "DeleteTier('"+id+"')");
	      $('#delete-tier').modal('show');
	      return false;
	    }
	    $('.tier_'+id).slideUp();
		$('.tier_'+id).remove();
		$('#edit_tier_modal_'+id).remove();
		$.post(Wo_Ajax_Requests_File() + '?f=tier&s=delete&hash=' + $('.main_session').val(), {id: id}, function(data, textStatus, xhr) {});
	}
	function AddTier(){
		$('.modal_add_tier_modal_alert').empty();
	  $("#add_tier_modal").find('.btn-main').removeAttr('disabled')
	  $("#add_tier_modal").find('.btn-main').text("<?php echo $wo['lang']['add'] ?>");
	  $('#add_tier_modal').modal('show');
	  $("#select_tier_image").click(function(event) {
      $("#tier_image").click()
    });
    $("#tier_image").change(function(event) {
      $("#select_tier_image").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
    });
	}
	function ShowBenefitsChat(self){
		if ($(self).prop("checked")) {
			$('.add_benefits_chat').slideDown();
		}
		else{
			$('.add_benefits_chat').slideUp();
		}
	}
	$(document).ready(function() { 
    var options = { 
      url: Wo_Ajax_Requests_File() + '?f=tier&s=add&hash=' + $('.main_session').val(),
        beforeSubmit:  function () {
          $('.modal_add_tier_modal_alert').empty();
          $("#add_tier_modal").find('.btn-main').attr('disabled', 'true');
          $("#add_tier_modal").find('.btn-main').text("<?php echo($wo['lang']['please_wait']) ?>");
        }, 
        success: function (data) {
          $("#add_tier_modal").find('.btn-main').text("<?php echo $wo['lang']['add'] ?>");
          $("#add_tier_modal").find('.btn-main').removeAttr('disabled')
          if (data.status == 200) {
            $('.modal_add_tier_modal_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> '+
              data.message
              +'</div>');
              setTimeout(function () {
                $('.modal_add_tier_modal_alert').empty();
	              $("#add_tier_modal").find('.btn-main').removeAttr('disabled')
	              $("#add_tier_modal").find('.btn-main').text("<?php echo $wo['lang']['add'] ?>");
	              $('#add_tier_modal').modal('hide');
	              location.reload();
              },2000);
          } else {
            $('.modal_add_tier_modal_alert').html('<div class="alert alert-danger"> '+
            data.message
            +'</div>');
          } 
        }
    }; 
    $('.tier_form').ajaxForm(options); 
  });
</script>