<h2 class="tag_page_title"><button type="button" class="btn setting_navigation" onclick="$('.tag_sett_sidebar').fadeIn(50);$('#tag_sett_right_prt').fadeOut(50);"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z" fill="currentColor"></path></svg></button> <?php echo $wo['lang']['two_factor']; ?></h2>
<div class="wow_sett_content wow_content p20">
	<form class="form-horizontal setting-change-password-form wo_settings_page" method="post">
		<div class="empty_state">
			<svg enable-background="new 0 0 32 32" height="512" viewBox="0 0 32 32" width="512" xmlns="http://www.w3.org/2000/svg"><path d="m26 32h-20c-3.314 0-6-2.686-6-6v-20c0-3.314 2.686-6 6-6h20c3.314 0 6 2.686 6 6v20c0 3.314-2.686 6-6 6z" fill="#f5e6fe"/><path d="m17.167 12.667h-.5v-1.333c0-1.839-1.496-3.334-3.334-3.334s-3.333 1.495-3.333 3.333v1.333h-.5c-.827 0-1.5.673-1.5 1.5v5.667c0 .827.673 1.5 1.5 1.5h7.667c.827 0 1.5-.673 1.5-1.5v-5.667c0-.826-.673-1.499-1.5-1.499zm-5.834-1.334c0-1.103.897-2 2-2s2 .897 2 2v1.333h-4z" fill="#be63f9"/><g fill="#d9a4fc"><path d="m21.334 20.667c-.735 0-1.333-.598-1.333-1.333s.597-1.334 1.333-1.334c.735 0 1.333.598 1.333 1.333s-.598 1.334-1.333 1.334z"/><path d="m23.5 24h-4.334c-.276 0-.5-.224-.5-.5v-.333c0-1.011.822-1.833 1.833-1.833h1.667c1.011 0 1.833.822 1.833 1.833v.333c.001.276-.223.5-.499.5z"/></g></svg> <?php echo $wo['lang']['two_factor_description'] ?>
		</div>
		<hr class="style-two">
		<br>
		<div class="setting-password-alert setting-update-alert"></div>
		<?php if ($wo['setting']['two_factor'] == '0') { ?>
			<label class="tag_field">
				<select id="two_factor_method" name="two_factor_method" onchange="showMethod(this)">
					<?php if ($wo['config']['two_factor'] == '1') { ?>
						<option value="two_factor" <?php echo ($wo['setting']['two_factor_method'] == 'two_factor') ? 'selected': '';?>><?php echo getTwoFactorText(); ?></option>
					<?php } ?>
					<?php if ($wo['config']['google_authenticator'] == '1') { ?>
					<option value="google" <?php echo ($wo['setting']['two_factor_method'] == 'google') ? 'selected': '';?>><?php echo $wo['lang']['google_authenticator']; ?></option>
					<?php } ?>
					<?php if ($wo['config']['authy_settings'] == '1') { ?>
					<option value="authy" <?php echo ($wo['setting']['two_factor_method'] == 'authy') ? 'selected': '';?>><?php echo $wo['lang']['authy_app']; ?></option>
					<?php } ?>
				</select>
				<span><?php echo $wo['lang']['two_factor_method']; ?></span>
			</label>

			<?php if ($wo['config']['google_authenticator'] == '1') { ?>
				<div class="google_authenticator" <?php if ($wo['setting']['two_factor_method'] != 'google') { ?>style="display:none;"<?php } ?>>
					<div class="wo_google_auth">
						<img src="<?php echo $wo['googleQR']; ?>">
						<label class="tag_field">
							<input id="verify_google_code" type="text" placeholder=" ">
							<span><?php echo $wo['lang']['confirm_code'] ?></span>
						</label>
					</div>
					<div class="wo_google_auth_info">
						<p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7 4V20H17V4H7ZM6 2H18C18.5523 2 19 2.44772 19 3V21C19 21.5523 18.5523 22 18 22H6C5.44772 22 5 21.5523 5 21V3C5 2.44772 5.44772 2 6 2ZM12 17C12.5523 17 13 17.4477 13 18C13 18.5523 12.5523 19 12 19C11.4477 19 11 18.5523 11 18C11 17.4477 11.4477 17 12 17Z"></path></svg> <span><?php echo $wo['lang']['authenticator_download']; ?></span></p>
						<p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M3 4.99509C3 3.89323 3.89262 3 4.99509 3H19.0049C20.1068 3 21 3.89262 21 4.99509V19.0049C21 20.1068 20.1074 21 19.0049 21H4.99509C3.89323 21 3 20.1074 3 19.0049V4.99509ZM5 5V19H19V5H5ZM7.97216 18.1808C7.35347 17.9129 6.76719 17.5843 6.22083 17.2024C7.46773 15.2753 9.63602 14 12.1022 14C14.5015 14 16.6189 15.2071 17.8801 17.0472C17.3438 17.4436 16.7664 17.7877 16.1555 18.0718C15.2472 16.8166 13.77 16 12.1022 16C10.3865 16 8.87271 16.8641 7.97216 18.1808ZM12 13C10.067 13 8.5 11.433 8.5 9.5C8.5 7.567 10.067 6 12 6C13.933 6 15.5 7.567 15.5 9.5C15.5 11.433 13.933 13 12 13ZM12 11C12.8284 11 13.5 10.3284 13.5 9.5C13.5 8.67157 12.8284 8 12 8C11.1716 8 10.5 8.67157 10.5 9.5C10.5 10.3284 11.1716 11 12 11Z"></path></svg> <span><?php echo $wo['lang']['authenticator_set']; ?></span></p>
						<p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M6.99979 7V3C6.99979 2.44772 7.4475 2 7.99979 2H20.9998C21.5521 2 21.9998 2.44772 21.9998 3V16C21.9998 16.5523 21.5521 17 20.9998 17H17V20.9925C17 21.5489 16.551 22 15.9925 22H3.00728C2.45086 22 2 21.5511 2 20.9925L2.00276 8.00748C2.00288 7.45107 2.4518 7 3.01025 7H6.99979ZM8.99979 7H15.9927C16.549 7 17 7.44892 17 8.00748V15H19.9998V4H8.99979V7ZM15 9H4.00255L4.00021 20H15V9ZM8.50242 18L4.96689 14.4645L6.3811 13.0503L8.50242 15.1716L12.7451 10.9289L14.1593 12.3431L8.50242 18Z"></path></svg> <span><?php echo $wo['lang']['authenticator_verify']; ?></span></p>
						<p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M18 8H20C20.5523 8 21 8.44772 21 9V21C21 21.5523 20.5523 22 20 22H4C3.44772 22 3 21.5523 3 21V9C3 8.44772 3.44772 8 4 8H6V7C6 3.68629 8.68629 1 12 1C15.3137 1 18 3.68629 18 7V8ZM5 10V20H19V10H5ZM11 14H13V16H11V14ZM7 14H9V16H7V14ZM15 14H17V16H15V14ZM16 8V7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7V8H16Z"></path></svg> <span><?php echo $wo['lang']['authenticator_otp']; ?></span></p>
					</div>
				</div>
			<?php } ?>
			<?php if ($wo['config']['authy_settings'] == '1') { ?>
				<?php //if (!empty($pt->settings->authy_id)) { ?>
					<div class="text-center" <?php if ($wo['setting']['two_factor_method'] != 'authy') { ?>style="display:none;"<?php } ?>>
						<img src="{{authyQR}}">
					</div>
				<?php //} ?>
			<?php } ?>
		<?php }else{ ?>
			<div class="empty_state">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M2,7V9H6V11H4A2,2 0 0,0 2,13V17H8V15H4V13H6A2,2 0 0,0 8,11V9C8,7.89 7.1,7 6,7H2M9,7V17H11V13H14V11H11V9H15V7H9M18,7A2,2 0 0,0 16,9V17H18V14H20V17H22V9A2,2 0 0,0 20,7H18M18,9H20V12H18V9Z"></path></svg> <?php echo(str_replace('{method}', $wo['factor_used'], $wo['lang']['two_auth_currenly_enabled'])) ?>
				<input type="hidden" name="two_factor" value="0">
			</div>
		<?php } ?>
        
		<?php if ($wo['config']['two_factor_type'] == 'both' || $wo['config']['two_factor_type'] == 'phone') { ?>
			<label class="tag_field">
				<input name="phone_number" id="phone_number" type="text" autocomplete="off" placeholder=" " value="<?php echo $wo['setting']['phone_number']?>">
				<span><?php echo $wo['lang']['phone_number']; ?></span>
			</label>
		<?php } ?>
		
		<input type="hidden" name="" id="two_factor_value">
		
		<div class="text-center">
			<?php if ($wo['setting']['two_factor'] == '0') { ?>
				<button type="button" id="request_code" class="btn btn-main btn-mat btn-mat-raised disable_btn" onclick="requestCode()"><?php echo $wo['lang']['save']; ?></button>
			<?php }else{ ?>
				<input type="hidden" name="two_factor" value="disable">
				<?php if ($wo['setting']['two_factor_method'] == 'authy' || $wo['setting']['two_factor_method'] == 'google') { ?>
					<button type="button" class="btn btn-main btn-mat btn-mat-raised disable_btn" id="download_backup_codes_btn" onclick="downloadBackup()"><?php echo $wo['lang']['download_backup_codes']; ?></button>
				<?php } ?>
				<button type="button" class="btn btn-main btn-mat btn-mat-raised disable_btn" id="submit_two_factor_btn"><?php echo $wo['lang']['deactivate']; ?></button>
			<?php } ?>
		</div>
		
		<input type="hidden" name="user_id" value="<?php echo $wo['setting']['user_id'];?>">
		<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
	</form>
</div>

<div class="modal fade" id="verify_modal" role="dialog">
    <div class="modal-dialog modal-md wow_mat_mdl">
        <div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><?php echo $wo['lang']['confirm_code']; ?></h4>
			</div>
            
			<form id="verify_form" method="post">
				<div class="modal-body">
					<div id="verify_alert" style="color: red;"></div>
                
                    <div class="authy_qr"></div>
					<label class="tag_field">
						<input id="verify_authy_code" type="text" placeholder=" ">
						<span><?php echo $wo['lang']['confirm_code']; ?></span>
					</label>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel'] ?></button>
					<button type="button" class="btn btn-main btn-mat disable_btn" onclick="verifyCode()" id="verify_code_button"><?php echo $wo['lang']['send']; ?></button>
				</div>
			</form>
        </div>
    </div>
</div>

<div class="modal fade" id="authy_modal" role="dialog">
    <div class="modal-dialog modal-md wow_mat_mdl">
        <div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><?php echo $wo['lang']['authy_register']; ?></h4>
			</div>
			<form id="authy_form" method="post">
				<div class="modal-body">
					<div id="authy_alert" style="color: red;"></div>
					
					<label class="tag_field">
						<input id="authy_email" type="text" placeholder=" " value="<?php echo $wo['setting']['email'];?>">
						<span><?php echo $wo['lang']['email']; ?></span>
					</label>
					
                    <div class="row">
                        <div class="col-md-4">
                            <label class="tag_field">
								<select id="country_code" name="country_code">
									<?php foreach ($wo['countries_codes'] as $key => $value) { ?>
										<option value="<?php echo($key) ?>"><?php echo($value) ?></option>
									<?php } ?>
								</select>
								<span><?php echo $wo['lang']['country_code']; ?></span>
							</label>
                        </div>
                        <div class="col-md-8">
							<label class="tag_field">
								<input id="authy_phone" type="text" placeholder=" " value="<?php echo $wo['setting']['phone_number'];?>">
								<span><?php echo $wo['lang']['phone_number']; ?></span>
							</label>
                        </div>
                    </div>
                    
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel'] ?></button>
					<button type="button" class="btn btn-main btn-mat disable_btn" onclick="authyRegister()" id="authy_button"><?php echo $wo['lang']['send']; ?></button>
				</div>
			</form>
        </div>
    </div>
</div>

<div class="modal fade" id="verify_code" role="dialog">
	<div class="modal-dialog wow_mat_mdl modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="two_factor_title">
					<?php 
						if ($wo['config']['two_factor_type'] == 'both') {
							echo $wo['lang']['confirmation_message_email_sent'];
						}
						elseif ($wo['config']['two_factor_type'] == 'email') {
							echo $wo['lang']['confirmation_email_sent'];
						}
						elseif ($wo['config']['two_factor_type'] == 'phone') {
							echo $wo['lang']['confirmation_message_sent'];
						}
					?>
				</h4>
			</div>
			<form id="confirmation_code_form" class="confirmation_code_form" method="POST">
				<div class="modal-body">
					<div id="confirmation_code_form_alert"></div>
					<p id="two_factor_desc">
						<?php 
							if ($wo['config']['two_factor_type'] == 'both') {
								echo $wo['lang']['confirmation_email_message_text'];
							}
							elseif ($wo['config']['two_factor_type'] == 'email') {
								echo $wo['lang']['confirmation_email_text'];
							}
							elseif ($wo['config']['two_factor_type'] == 'phone') {
								echo $wo['lang']['confirmation_message_text'];
							}
						?>
					</p>
					<div class="form-group">
						<input type="text" class="tag_confrm_code_input" name="code" placeholder="<?php echo $wo['lang']['confirmation_code']; ?>">
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel'] ?></button>
					<button id="confirmation_code_form_btn" type="submit" class="btn btn-main btn-mat disable_btn"><?php echo $wo['lang']['verify']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
function downloadBackup() {
        $('#download_backup_codes_btn').text("<?php echo $wo['lang']['please_wait']; ?>");
        $.post(Wo_Ajax_Requests_File() + '?f=update_two_factor&s=backup_codes', {user_id: "<?php echo $wo['setting']['user_id'];?>"}, function(data, textStatus, xhr) {
            $('#download_backup_codes_btn').text("<?php echo $wo['lang']['download_backup_codes']; ?>");

            var blob = new Blob([data], {type: 'text/plain'});
            var url = URL.createObjectURL(blob);
            var a = document.createElement('a');
            a.href = url;
            a.download = 'backup-codes.txt';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        });
    }
  <?php if ($wo['setting']['two_factor'] == '0') { ?>
	var submitgooogle = document.getElementById("verify_google_code");
		submitgooogle.addEventListener("keydown", function (e) {
			if (e.code === "Enter") {  //checks whether the pressed key is "Enter"
				event.preventDefault();
				verifyGoogleCode();
				return false;
			}
		});
		
    function verifyCode() {
        $('#verify_code_button').text("<?php echo $wo['lang']['please_wait']; ?>");
        $.post(Wo_Ajax_Requests_File() + '?f=update_two_factor&s=verify_code', {user_id: "<?php echo $wo['setting']['user_id'];?>", code: $('#verify_authy_code').val(), factor_method: $('#two_factor_method').val()}, function(data, textStatus, xhr) {
            $('#verify_code_button').text("<?php echo $wo['lang']['send']; ?>");
            if (data.status == 200) {
                $('#verify_alert').html('<div class="alert alert-success">' + data.message + '</div>');
                setTimeout(() => {
                    $('#verify_alert').html('');
                    window.location.reload();
                },2000);
            }
            else{
                $('#verify_alert').html('<div class="alert alert-danger">' + data.message + '</div>');
                setTimeout(() => {
                    $('#verify_alert').html('');
                },2000);
            }
        });
    }
    function authyRegister() {
        $('#authy_button').text("<?php echo $wo['lang']['please_wait']; ?>");
        $.post(Wo_Ajax_Requests_File() + '?f=update_two_factor&s=authy_register', {user_id: "<?php echo $wo['setting']['user_id'];?>", email: $('#authy_email').val(), phone: $('#authy_phone').val(), country_code: $('#country_code').val()}, function(data, textStatus, xhr) {
            $('#authy_button').text("<?php echo $wo['lang']['send']; ?>");
            if (data.status == 200) {
                $('#authy_alert').html('<div class="alert alert-success">' + data.message + '</div>');
                setTimeout(() => {
                    $('#authy_alert').html('');
                    $('#authy_modal').modal('hide');
                    
                    if (typeof data.qr != 'undefined' && data.qr != '') {
                        $('#verify_modal').modal({
                         show: true
                        });
                        $('.authy_qr').html('<img src="'+data.qr+'">');
                    }
                    else{
                        window.location.reload();
                    }
                },2000);
            }
            else{
                $('#authy_alert').html('<div class="alert alert-danger">' + data.message + '</div>');
                setTimeout(() => {
                    $('#authy_alert').html('');
                },2000);
            }
        });
    }
    function verifyGoogleCode() {
        $('#request_code').text("<?php echo $wo['lang']['please_wait']; ?>");
        $.post(Wo_Ajax_Requests_File() + '?f=update_two_factor&s=verify_code', {user_id: "<?php echo $wo['setting']['user_id'];?>", code: $('#verify_google_code').val(), factor_method: $('#two_factor_method').val()}, function(data, textStatus, xhr) {
            $('#request_code').text("<?php echo $wo['lang']['save']; ?>");
            if (data.status == 200) {
                $('.setting-password-alert').html('<div class="alert alert-success">' + data.message + '</div>');
                setTimeout(() => {
                    $('.setting-password-alert').html('');
                    window.location.reload();
                },2000);
            }
            else{
                $('.setting-password-alert').html('<div class="alert alert-danger">' + data.message + '</div>');
                setTimeout(() => {
                    $('.setting-password-alert').html('');
                },2000);
            }
        });
    }
    function requestCode() {
        if ($('#two_factor_method').val() == 'google') {
            verifyGoogleCode();
            return false;
        }
        
        if ($('#two_factor_method').val() == 'authy') {
            <?php if (empty($wo['setting']['authy_id'])) { ?>
              $('#authy_modal').modal({
               show: true
              });
            <?php }else{ ?>
              $('#verify_modal').modal({
                         show: true
                        });
            <?php } ?>
            return false;
        }
        
        $('#request_code').text("<?php echo $wo['lang']['please_wait']; ?>");
        $.post(Wo_Ajax_Requests_File() + '?f=update_two_factor&s=enable', {user_id: "<?php echo $wo['setting']['user_id'];?>", factor_method: $('#two_factor_method').val(), phone_number: $('#phone_number').val()}, function(data, textStatus, xhr) {
            $('#request_code').text("<?php echo $wo['lang']['save']; ?>");
            if (data.status == 200) {
                $('.setting-password-alert').html('<div class="alert alert-success">' + data.message + '</div>');
                $('.alert-success').fadeIn(300);
                $('#verify_code').modal('show');
            }
            else{
                $('.setting-password-alert').html('<div class="alert alert-danger">' + data.message + '</div>');
                $('.alert-danger').fadeIn(300);
            }
        });
    }
  <?php } ?>
  $(document).ready(function() {
    showMethod('#two_factor_method');
  });
  function showMethod(self) {
        if ($(self).val() == 'google') {
            $('.google_authenticator').slideDown();
            $('.authy_auth').slideUp();
        }
        else if($(self).val() == 'authy') {
            $('.authy_auth').slideDown();
            $('.google_authenticator').slideUp();
        }
        else{
            $('.google_authenticator').slideUp();
            $('.authy_auth').slideUp();
        }
    }

  $(document).on('click', '#submit_two_factor_btn', function(event) {
    $.ajax({
    url: Wo_Ajax_Requests_File() + '?f=update_two_factor&s=disable',
    type: 'POST',
    data:$('form.setting-change-password-form').serialize(),
    beforeSend: function() {
      $('.wo_settings_page').find('.disable_btn').attr('disabled','disabled');
    },
    success: function(data) {
      if (data.status == 200) {
        $('.setting-password-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          $(this).delay(2000).slideUp(500, function() {
              location.reload();
          });
        });
      } else if (data.status == 400) {
        $('.setting-password-alert').html('<div class="alert alert-danger">' + data.message + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      $('.wo_settings_page').find('.disable_btn').removeAttr("disabled");
    }
  });
    
  });
$(function() {

  $('form.confirmation_code_form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_two_factor&s=verify',
    beforeSend: function() {
      $('#confirmation_code_form_btn').text('<?php echo($wo['lang']['please_wait']) ?>');
    },
    success: function(data) {
      if (data.status == 200) {
        $('#confirmation_code_form_alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('#confirmation_code_form_alert').fadeIn('fast', function() {
          $(this).delay(2500).slideUp(500, function() {
              $(this).remove();
              $('#verify_code').modal('hide');
              location.reload();
          });
        });
      } else if (data.status == 400) {
        $('#confirmation_code_form_alert').html('<div class="alert alert-danger">' + data.message + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      $('#confirmation_code_form_btn').text('<?php echo($wo['lang']['send']) ?>');
    }
  });
});

$(document).ready(function() {
    $('.tag_confrm_code_input').codeInput({
        number: 6
    });
});

jQuery.fn.codeInput = function(options) {
    var defaults = {
        number: 4,
        length: 1
    };

    var settings = $.extend({}, defaults, options);

    return this.each(function() {
        var self = $(this);
        var placeholder = self.attr('placeholder');
        var div = $('<div />').addClass('tag_confrm_code');
        div.append($('<span />').text(placeholder));
        self.replaceWith(div);
        div.append(self);
        var inputDiv = $('<div />').addClass('inputs');
        for(var i = 1; i <= settings.number; i++) {
            inputDiv.append($('<input />').attr({
                maxlength: settings.length
            }));
        }

        div.prepend(inputDiv);

        div.on('click touchstart', function(e) {
            if(!div.hasClass('active')) {
                div.addClass('active');
                setTimeout(function() {
                    div.find('.inputs input:first-child').focus();
                }, 100);
            }
        });

        div.find('.inputs').on('keyup input', 'input', function(e) {
            if($(this).val().toString().length >= settings.length || e.keyCode == 39) {
                $(this).next().focus();
            }
            if(e.keyCode == 8 || e.keyCode == 37) {
                $(this).prev().focus();
            }
            var value = '';
            div.find('.inputs input').each(function() {
                value = value + $(this).val().toString();
            });
            self.attr({
                value: value
            });
        });

        $(document).on('click touchstart', function(e) {
            if(!$(e.target).parent().is(div) && !$(e.target).parent().parent().is(div)) {
                var hide = true;
                div.find('.inputs input').each(function() {
                    if($(this).val().toString().length) {
                        hide = false;
                    }
                });
                if(hide) {
                    div.removeClass('active');
                    div.find('.inputs input').blur();
                } else {
                    div.addClass('active');
                }
            }
        });

    });
}
</script>