<button type="button" data-uch='{"id":"<?php echo $wo['message']['user_id'];?>","fullname":"<?php if(empty($wo['message']['first_name'])) echo $wo['message']['username']; else echo $wo['message']['first_name'].' '.$wo['message']['last_name'];?>","photo":"<?php echo $wo['message']['avatar'];?>"}' class="btn btn-default btn-sm" onclick="vy_openChatTab(this,event,<?php echo $wo['message']['user_id'];?>);">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-square"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg>
<span class="button-text"> <?php echo $wo['lang']['message'];?></span>
</button>
 
 