<div class="col-6 col-sm-6 col-md-4 col-lg-3 nearby_user_wrapper user-data" data-family-member="<?php echo $wo['UsersList']['user_data']['user_id'];?>">
	<div class="nearby_user_wrapper_innr text-center">
		<div class="avatar">
			<a href="<?php echo $wo['UsersList']['user_data']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['user_data']['username'];?>"><img src="<?php echo $wo['UsersList']['user_data']['avatar'];?>" alt="<?php echo $wo['UsersList']['user_data']['name']; ?>" /></a>
		</div>
		<span class="user-popover" data-id="<?php echo $wo['UsersList']['user_data']['id'];?>" data-type="<?php echo $wo['UsersList']['user_data']['type'];?>">
			<a href="<?php echo $wo['UsersList']['user_data']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['user_data']['username'];?>" class="truncate user_wrapper_link"><?php echo $wo['UsersList']['user_data']['name']; ?></a>
			<?php if (!empty($wo['UsersList']['is_open_to_work']) && $wo['config']['website_mode'] == 'linkedin') { ?>
				<span class="wo_open_job_badge" title="<?php echo($wo['lang']['open_to_work']); ?>" data-toggle="tooltip"><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" viewBox="0 0 24 24"><path fill="currentColor" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z"></path></svg></span>
			<?php } ?>
		</span>
		<div class="user-lastseen"><?php echo $wo['lang'][$wo['family'][$wo['UsersList']['member']]];?></div>
		<div class="user-follow-button">
			<?php if ($wo['UsersList']['active'] == 1 && $wo['user_profile']['id'] == $wo['user']['id']): ?>
				<button type="button" class="btn btn-default btn-mat" onclick="$('#delete_family_mbr_modal').attr('data-family-member-id', '<?php echo $wo['UsersList']['user_data']['id'];?>').modal('show');"><?php echo $wo['lang']['delete'];?></button>
			<?php endif; ?>
		</div>
	</div>
</div>