<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfdcf5abf6642d2444c47335f2c7036ff
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'Emojione\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Emojione\\' => 
        array (
            0 => __DIR__ . '/..' . '/emojione/emojione/lib/php/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfdcf5abf6642d2444c47335f2c7036ff::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfdcf5abf6642d2444c47335f2c7036ff::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
