<?php if ($wo['story']['multi_image'] == 1) { ?>
    <div class="scrolling-wrapper">
        <?php foreach ($wo['story']['photo_multi'] as $photo) {
            $imageSrc = Wo_GetMedia($photo['image_org']);
            $imageAlt = "Image " . $photo['id']; // Replace with actual alt text if available
            ?>
            <div class="image-container">
                <img src="<?php echo $imageSrc ?>" alt="<?php echo $imageAlt ?>" onclick="openLightbox('<?php echo $imageSrc ?>', '<?php echo $imageAlt ?>')">
            </div>
        <?php } ?>
    </div>
<?php } ?>

<div id="lightbox" class="lightbox-hidden">
    <span class="lightbox-close" onclick="closeLightbox()">&times;</span>
    <img class="lightbox-content" id="lightbox-image">
    <div id="lightbox-caption"></div>
</div>

<style>
.scrolling-wrapper {
    overflow-x: scroll;
    overflow-y: hidden;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
}
.image-container {
    display: inline-block;
    width: 50.66%; /* 100% / 6 */
}
.image-container img {
    width: 100%;
    height: auto;
	border-radius: 25px;
}

.lightbox-hidden {
    display: none;
    position: fixed;
    z-index: 9999;
    padding-top: 100px;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0,0.9);
}

.lightbox-content {
    margin: auto;
    display: block;
    width: 100%;
    max-width: 700px;
	object-fit: contain;
}

.lightbox-close {
    position: absolute;
    top: 15px;
    right: 35px;
    color: #f1f1f1;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
	z-index: 9999;
}

.lightbox-close:hover,
.lightbox-close:focus {
    color: #bbb;
    text-decoration: none;
    cursor: pointer;
}
</style>

<script>
function openLightbox(imageSrc, imageAlt) {
    document.getElementById('lightbox').style.display = "block";
    document.getElementById('lightbox-image').src = imageSrc;
    document.getElementById('lightbox-caption').innerHTML = imageAlt;
}

function closeLightbox() {
    document.getElementById('lightbox').style.display = "none";
}
</script>
