<div class="wow_content shadow-none wo_job_detail_block">
	<div class="wo_job_experience">
		<div class="avatar">
			<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>">
				<img src="<?php echo $wo['UsersList']['avatar'];?>" alt="<?php echo $wo['UsersList']['name']; ?> Profile Picture"/>
			</a>
		</div>&nbsp;&nbsp;&nbsp;&nbsp;
		<div class="wo_job_experience_info">
			<h4 class="title">
				<span class="user-popover" data-id="<?php echo $wo['UsersList']['id'];?>" data-type="<?php echo $wo['UsersList']['type'];?>">
					<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>"><?php echo $wo['UsersList']['name']; ?>
					<?php if (!empty($wo['UsersList']['is_open_to_work']) && $wo['config']['website_mode'] == 'linkedin') { ?>
						<span class="wo_open_job_badge" title="<?php echo($wo['lang']['open_to_work']); ?>" data-toggle="tooltip"><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" viewBox="0 0 24 24"><path fill="currentColor" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z"></path></svg></span>
					<?php } ?>
					</a>
				</span>
			</h4>
			<div class="wo_job_detail_item">
				<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M11,13.5V21.5H3V13.5H11M12,2L17.5,11H6.5L12,2M17.5,13C20,13 22,15 22,17.5C22,20 20,22 17.5,22C15,22 13,20 13,17.5C13,15 15,13 17.5,13Z"></path></svg>&nbsp;
				<div>
					<h4><?php echo($wo['lang']['services']); ?></h4>
					<p><?php echo $wo['UsersList']['providing_service']->services; ?></p>
				</div>
			</div>
			<p class="user-follow-button">
				<?php echo Wo_GetFollowButton($wo['UsersList']['user_id']);?>
			</p>
		</div>
	</div>
</div>